-- 코드를 입력하세요
SELECT      A.CAR_ID
        ,   ROUND(SUM(END_DATE - START_DATE + 1)/COUNT(HISTORY_ID),1)   AVERAGE_DURATION
FROM        CAR_RENTAL_COMPANY_RENTAL_HISTORY   A
GROUP BY    A.CAR_ID
HAVING      ROUND(SUM(END_DATE - START_DATE + 1)/COUNT(HISTORY_ID),1) >= 7 
ORDER BY    2 DESC, 1 DESC