SELECT A.ID, A. NAME, A.HOST_ID
FROM PLACES A
INNER JOIN (SELECT HOST_ID,
                COUNT(HOST_ID) AS COUNT
            FROM PLACES
            GROUP BY HOST_ID) B
ON A.HOST_ID = B.HOST_ID
WHERE COUNT > 1
ORDER BY 1 ASC